#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HowManyDaysTil.Web.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Home\_Events.cshtml"
    using HowManyDaysTil.Web.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/_Events.cshtml")]
    public partial class Events : System.Web.Mvc.WebViewPage<HowManyDaysTil.Web.Models.HomeViewModel>
    {
        public Events()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"span6\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"your-upcoming-events\"");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n");

            
            #line 7 "..\..\Views\Home\_Events.cshtml"
            
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\Home\_Events.cshtml"
             if (Request.IsAuthenticated)
            {
                if (Model.CalendarEvents.Any())
                {

            
            #line default
            #line hidden
WriteLiteral("                <h1>Your upcoming ");

            
            #line 11 "..\..\Views\Home\_Events.cshtml"
                             Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" events</h1>\r\n");

WriteLiteral("                <br />\r\n");

            
            #line 13 "..\..\Views\Home\_Events.cshtml"
                    foreach (var calendarEvent in Model.CalendarEvents)
                    {
                        
               

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"span6\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"span5\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"calendar\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"month\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\Home\_Events.cshtml"
                                               Write(Html.GetMonthName(calendarEvent.CalendarEventDate));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <span");

WriteLiteral(" class=\"day\"");

WriteLiteral(">");

            
            #line 22 "..\..\Views\Home\_Events.cshtml"
                                             Write(calendarEvent.CalendarEventDate.Day);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </div>\r\n                            <h3>");

            
            #line 24 "..\..\Views\Home\_Events.cshtml"
                           Write(calendarEvent.Name);

            
            #line default
            #line hidden
WriteLiteral(" </h3>\r\n                            <span");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n");

            
            #line 26 "..\..\Views\Home\_Events.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Home\_Events.cshtml"
                                 using (Html.BeginForm("DeleteEvent", "Home", new { @id = calendarEvent.CalendarEventId }, FormMethod.Post, new { @id = "deleteEventForm" }))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" title=\"edit event\"");

WriteLiteral(" style=\"cursor: pointer\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1385), Tuple.Create("\"", 1483)
, Tuple.Create(Tuple.Create("", 1395), Tuple.Create("showModal(\'#editModalContainerID\',", 1395), true)
, Tuple.Create(Tuple.Create(" ", 1429), Tuple.Create("\'#editModalBodyID\',", 1430), true)
, Tuple.Create(Tuple.Create(" ", 1449), Tuple.Create("\'", 1450), true)
            
            #line 28 "..\..\Views\Home\_Events.cshtml"
                                                                                       , Tuple.Create(Tuple.Create("", 1451), Tuple.Create<System.Object, System.Int32>(calendarEvent.CalendarEventId
            
            #line default
            #line hidden
, 1451), false)
, Tuple.Create(Tuple.Create("", 1481), Tuple.Create("\')", 1481), true)
);

WriteLiteral("><i");

WriteLiteral(" class=\"icon-edit\"");

WriteLiteral("></i></a>\r\n");

WriteLiteral("                                    <a");

WriteLiteral(" data-id=\"");

            
            #line 29 "..\..\Views\Home\_Events.cshtml"
                                           Write(calendarEvent.CalendarEventId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-name=\"");

            
            #line 29 "..\..\Views\Home\_Events.cshtml"
                                                                                      Write(calendarEvent.Name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"remove event\"");

WriteLiteral(" class=\"removeItem\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-remove\"");

WriteLiteral("></i></a>\r\n");

            
            #line 30 "..\..\Views\Home\_Events.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </span>\r\n                            <span");

WriteLiteral(" class=\"label label-info\"");

WriteLiteral(">");

            
            #line 32 "..\..\Views\Home\_Events.cshtml"
                                                      Write(Html.DisplayDaysLeft(calendarEvent.CalendarEventDate));

            
            #line default
            #line hidden
WriteLiteral("</span><br />\r\n\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n");

WriteLiteral("                <hr />\r\n");

            
            #line 38 "..\..\Views\Home\_Events.cshtml"
                
                    }

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteLiteral(" class=\"hidden-desktop pull-right\"");

WriteLiteral(" onclick=\"$(\'html,body\').animate({scrollTop: $(\'#infoyou\').offset().top}, 1500);\"" +
"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-circle-arrow-up\"");

WriteLiteral(" style=\"cursor: pointer; text-decoration: none;\"");

WriteLiteral("></i></a>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

            
            #line 42 "..\..\Views\Home\_Events.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                <h2>Please take a moment to add an event!</h2>\r\n");

            
            #line 46 "..\..\Views\Home\_Events.cshtml"
                }
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <h2>Sign in below to start adding events</h2>\r\n");

WriteLiteral("                <br />\r\n");

            
            #line 52 "..\..\Views\Home\_Events.cshtml"
                using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = ViewBag.ReturnUrl }))
                {
                
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Home\_Events.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Home\_Events.cshtml"
                                        

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"hidden-phone\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"provider\"");

WriteLiteral(" class=\"zocial facebook\"");

WriteLiteral(" value=\"facebook\"");

WriteLiteral(" title=\"Sign in using your Facebook account\"");

WriteLiteral(" style=\"display: inline-block;\"");

WriteLiteral(">Sign in with Facebook</button>\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"provider\"");

WriteLiteral(" class=\"zocial twitter\"");

WriteLiteral(" value=\"twitter\"");

WriteLiteral(" title=\"Sign in using your Twitter account\"");

WriteLiteral(" style=\"display: inline-block;\"");

WriteLiteral(">Sign in with Twitter</button>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"hidden-desktop\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"provider\"");

WriteLiteral(" class=\"zocial facebook\"");

WriteLiteral(" value=\"facebook\"");

WriteLiteral(" title=\"Sign in using your Facebook account\"");

WriteLiteral(" style=\"display: inline-block;\"");

WriteLiteral(">Sign in with Facebook</button><br />\r\n                    <br />\r\n              " +
"      <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"provider\"");

WriteLiteral(" class=\"zocial twitter\"");

WriteLiteral(" value=\"twitter\"");

WriteLiteral(" title=\"Sign in using your Twitter account\"");

WriteLiteral(" style=\"display: inline-block;\"");

WriteLiteral(">Sign in with Twitter</button>\r\n                </div>\r\n");

            
            #line 64 "..\..\Views\Home\_Events.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <h3>Never forget important events! Here\'s a sample</h3>\r\n");

WriteLiteral("                <br />\r\n");

WriteLiteral("                <p>\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3926), Tuple.Create("\"", 3951)
, Tuple.Create(Tuple.Create("", 3932), Tuple.Create<System.Object, System.Int32>(Href("~/Images/sample.PNG")
, 3932), false)
);

WriteLiteral(" />\r\n                </p>\r\n");

            
            #line 70 "..\..\Views\Home\_Events.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"editModalContainerID\"");

WriteLiteral(" class=\"modal hide fade in\"");

WriteLiteral(" data-url=\'");

            
            #line 76 "..\..\Views\Home\_Events.cshtml"
                                                               Write(Url.Action("EditEvent", "Home"));

            
            #line default
            #line hidden
WriteLiteral("\'");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"editModalBodyID\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
