#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaysUntoWeb.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/_AddEvent.cshtml")]
    public partial class AddEvent : System.Web.Mvc.WebViewPage<dynamic>
    {
        public AddEvent()
        {
        }
        public override void Execute()
        {
WriteLiteral("<hr");

WriteLiteral(" style=\"margin: 0;\"");

WriteLiteral(" />\r\n<div");

WriteLiteral(" class=\"well-small\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" style=\"padding-bottom: 4px;\"");

WriteLiteral(">Add Events  ");

            
            #line 3 "..\..\Views\Home\_AddEvent.cshtml"
                                            Write(Html.ActionLink("Sign Out", "LogOff", "Account", null, new { @class = "btn pull-right", @style = "margin-top:8px;" }));

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n    Manual Entry<br />\r\n");

            
            #line 5 "..\..\Views\Home\_AddEvent.cshtml"
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Home\_AddEvent.cshtml"
     using (Html.BeginForm("ManualEntry", "Home", FormMethod.Post, new {@id = "entry-form"}))
    {

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" class=\"input-medium\"");

WriteLiteral(" name=\"calendarName\"");

WriteLiteral(" id=\"calendarName\"");

WriteLiteral(" placeholder=\"Name\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" required />\r\n");

WriteLiteral("        <input");

WriteLiteral(" class=\"input-medium datepicker\"");

WriteLiteral(" name=\"calendarDate\"");

WriteLiteral(" id=\"calendarDate\"");

WriteLiteral(" placeholder=\"Date\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" required");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" />\r\n");

WriteLiteral("        <button");

WriteLiteral(" class=\"btn\"");

WriteLiteral(" style=\"vertical-align: top;\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">Add</button>\r\n");

            
            #line 10 "..\..\Views\Home\_AddEvent.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    Import your calendar (.ics) file.<br />\r\n");

            
            #line 12 "..\..\Views\Home\_AddEvent.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Home\_AddEvent.cshtml"
     using (Html.BeginForm("ImportCalendar", "Home", FormMethod.Post, new {enctype = "multipart/form-data"}))
    {


            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" class=\"input-file\"");

WriteLiteral(" name=\"calendarfile\"");

WriteLiteral(" title=\"Select Calendar File\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" required />\r\n");

WriteLiteral("        <button");

WriteLiteral(" class=\"btn\"");

WriteLiteral(" style=\"vertical-align: top;\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"importCalendar\"");

WriteLiteral(">Import</button>\r\n");

            
            #line 17 "..\..\Views\Home\_AddEvent.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

        }
    }
}
#pragma warning restore 1591
